[project]
name = "region-aware-vision-assistant"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "onnxruntime",
    "opencv-python-headless",
    "numpy",
    "torch",
    "torchvision",
    "langchain",
    "langchain-qdrant",
    "langchain-huggingface",
    "langchain-ollama",
    "qdrant-client",
    "sentence-transformers",
]